---
id: "00008"
alias: Back Door - Not Home
trigger:
  - entity_id: binary_sensor.back_door
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: device_tracker.robert_iphone
    state: not_home
  - condition: state
    entity_id: device_tracker.john_iphone
    state: not_home
action:
  - data:
      title: Back Door
      message: Back door opened when nobody is home
    service: script.text_notify_john
