---
id: "00007"
alias: Door Open - HVAC Running
initial_state: true
trigger:
  - platform: state
    entity_id:
      - binary_sensor.front_door
      - binary_sensor.back_door
      - binary_sensor.garage_door
    to: "on"
    for:
      hours: 0
      minutes: 5
      seconds: 0
condition:
  - condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: climate.thermostat
            state: cool
          - condition: state
            entity_id: climate.thermostat
            state: heat
      - condition: template
        value_template: >-
          {{ ((states('sensor.outside_temperature', 'state') | float -
          state_attr('climate.thermostat', 'temperature')  | float) | abs) > 5
          }}
action:
  - service: script.text_notify_all
    data_template:
      title: HVAC Notice!
      message: >-
        The {{ state_attr('trigger.to_state', 'friendly_name') }} has been
        open for 5 minutes while the HVAC is on.
        It's {{
          (
            (state_attr('climate.thermostat', 'temperature') | int )
            -
            (states('sensor.outside_temperature', 'state') | int)
          ) | abs
        }} degrees different outside than the set 
        {{
          (states('climate.thermostat', 'state'))
        }} temperature!
      data:
        subtitle: >-
          {{ state_attr('trigger.to_state', 'friendly_name') }} Left Open!
