---
id: "00029"
alias: Dryer Active
trigger:
  platform: state
  entity_id: binary_sensor.dryer_dry_completed
  to: "off"
action:
  - service: light.turn_on
    target:
      entity_id: light.fairy_lights
    data:
      rgb_color:
        - 255
        - 65
        - 12
      transition: 5
