---
id: "00030"
alias: Dryer Done
trigger:
  platform: state
  entity_id: binary_sensor.dryer_dry_completed
  to: "on"
action:
  - service: light.turn_off
    target:
      entity_id: light.fairy_lights
  - service: counter.decrement
    target:
      entity_id: counter.laundry_queue
  - service: esphome.ulanzi_del_screen
    data:
      icon_name: laundry
