---
id: "00029"
alias: Dryer Active
trigger:
  platform: numeric_state
  entity_id: sensor.dryer_hem_power
  above: 3
action:
  - service: light.turn_on
    target:
      entity_id: light.fairy_lights
    data:
      rgb_color:
        - 255
        - 65
        - 12
      transition: 5
