---
id: "00023"
alias: Laundry Done
trigger:
  platform: numeric_state
  entity_id: sensor.laundry_power_electric_consumed_w
  below: 3000
  for:
    minutes: 2
action:
  - service: counter.increment
    target:
      entity_id: counter.laundry_queue
  - service: notify.alexa_media_living_room_dot
    data:
      message: >-
        The washing machine is finished. Please move the clothes to the dryer to
        prevent mildew.
      data:
        type: tts
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: awtrix_4200c8/custom/washerstate
      payload: |-
        {
          "text": "Washing machine is finished!",
          "icon": "24504",
          "rainbow": true,
          "repeat": 5,
          "duration": 10
        }
  - repeat:
      count: 1
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 100
            effect: Fireworks
          target:
            entity_id: light.east_lamp
        - delay:
            hours: 0
            minutes: 0
            seconds: 10
            milliseconds: 0
        - service: scene.apply
          data:
            entity_id: scene.before_wash
            transition: 5
  - service: scene.delete
    target:
      entity_id: scene.before_wash
