---
id: "00023"
alias: Laundry Done
trigger:
  platform: numeric_state
  entity_id: sensor.laundry_power_electric_consumed_w
  below: 3000
  for:
    minutes: 2
action:
  - service: light.turn_off
    target:
      entity_id: light.tree_light
  - service: notify.alexa_media_living_room_dot
    data:
      message: >-
        The washing machine is finished.
        Please move the clothes to the dryer to prevent mildew.
      data:
        type: tts
  - service: counter.increment
    target:
      entity_id: counter.laundry_queue
