---
id: "00033"
alias: Laundry Queue Alerts
trigger:
  - platform: time_pattern
    minutes: "/15"
    seconds: "00"
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: counter.laundry_queue
        above: 0
      - condition: state
        entity_id: binary_sensor.dryer_dry_completed
        state: "on"
action:
  - variables:
      # yamllint disable-line rule:line-length
      ulanzi_message: >
        There
        {%- if states("counter.laundry_queue") | int == 1 -%}
          {{- " is 1 load " -}}
        {%- else -%}
          {{- " are " + states("counter.laundry_queue") + " loads " -}}
        {%- endif -%}
        of clothes waiting for the dryer
  - service: notify.alexa_media
    data:
      title: Laundry Queue
      # yamllint disable rule:line-length
      message: >-
        {{
          [
            "Attention, laundry superhero! The wet garments need a new home in the dryer.",
            "Don't forget about the wet laundry",
            "Don't leave your clothes hanging, they've got drying dreams!",
            "Don't let your socks stage a damp rebellion. Dryer time!",
            "Hark! The dryer awaits, and the wet clothes demand an audience.",
            "Laundry delay: your shirts are contemplating a wet T-shirt contest. Move them to the dryer!",
            "Put the laundry in the dryer, or you'll be naked at work tomorrow",
            "Sir, your clothes are ready for their world tour. Time to move them to the dryer!",
            "The laundry is finished, don't let it mildew",
            "The washing machine is getting lonely. It's time for a dryer date!",
            "The washing machine's whispering secrets, time to uncover them in the dryer.",
            "There are wet clothes in the washing machine",
            "Time to cycle the wash",
            "Wet laundry needs to be moved to the dryer",
            "Your clothes are getting stinky. Move them to the dryer",
            "Your clothes are staging a sit-in protest in the washing machine. Relocate them to the dryer, stat!",
            "Your laundry is experiencing FOMO: Fear Of Missing Out on the dryer party!"
          ] | random
        }}
      # yamllint enable rule:line-length
      target:
        - media_player.bathroom_flex
        - media_player.bedroom_dot
        - media_player.computer_room_spot
        - media_player.kitchen_show
        - media_player.living_room_dot
      data:
        type: announce
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      payload: >-
        {
          "icon": 54961,
          "text": "{{ ulanzi_message }}",
          "rainbow": true,
          "duration": 10
        }
      topic: awtrix_4200c8/notify
