---
id: "00022"
alias: Laundry Active
trigger:
  platform: numeric_state
  entity_id: sensor.laundry_power_electric_consumed_w
  above: 3000
action:
  - service: scene.create
    metadata: {}
    data:
      scene_id: before_wash
      snapshot_entities:
        - light.east_lamp
  - service: light.turn_on
    target:
      entity_id: light.east_lamp
    data:
      color_temp: 255
      transition: 5
      brightness_pct: 50
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: awtrix_4200c8/custom/washerstate
      payload: >-
        {
          "text": "Washing machine is running...",
          "icon": "24502",
          "duration": 10
        }
