---
- id: "1658054420994"
  alias: Lights Out Received
  description: ""
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: Lights Out
  condition: []
  action:
    - service: light.turn_off
      data: {}
      target:
        area_id:
          - 1614066b49a34fe9949375f3bf26a223
          - 7b025e0c3c7641638e73e853646939b4
          - e16753df0a2c4302ac666b6cd9ff6503
          - dining_room
          - 1041436170a94090b8c3e1036fdc790b
          - bd498a7da6f14d68bbbb7ff210758418
          - stairwel
  mode: single
- id: "1683654483021"
  alias: "Den Becomes Occupied "
  description: ""
  trigger:
    - type: not_occupied
      platform: device
      device_id: 79bdefd124ef0ead386b37d759a02198
      entity_id: f3f3830cfc70dc3f508a98a3289e5a95
      domain: binary_sensor
  condition:
    - condition: device
      type: is_off
      device_id: 7d273c3380460516463f28d71c47f519
      entity_id: light.desk_lights
      domain: light
  action:
    - if:
        - condition: and
          conditions:
            - condition: time
              after: "23:00:00"
              weekday:
                - sun
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
            - condition: time
              before: 07:30:00
              weekday:
                - sun
                - mon
                - tue
                - wed
                - thu
                - fri
                - sat
      then:
        - type: turn_on
          device_id: 7d273c3380460516463f28d71c47f519
          entity_id: light.desk_lights
          domain: light
          brightness_pct: 50
      else:
        - type: turn_on
          device_id: 7d273c3380460516463f28d71c47f519
          entity_id: light.desk_lights
          domain: light
          brightness_pct: 100
  mode: restart
- id: "1683655257544"
  alias: "Den Becomes Unoccupied "
  description: ""
  trigger:
    - type: not_occupied
      platform: device
      device_id: 79bdefd124ef0ead386b37d759a02198
      entity_id: f3f3830cfc70dc3f508a98a3289e5a95
      domain: binary_sensor
  condition:
    - condition: device
      type: is_on
      device_id: 7d273c3380460516463f28d71c47f519
      entity_id: light.desk_lights
      domain: light
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
    - type: turn_off
      device_id: 7d273c3380460516463f28d71c47f519
      entity_id: light.desk_lights
      domain: light
  mode: single
