---
id: "00051"
alias: Carbon Monoxide Detected
description: "Send a warning that carbon monoxide was detected in the house."
mode: single
trigger:
  platform: state
  entity_id:
    - binary_sensor.guest_smoke_carbon_monoxide_detected
    - binary_sensor.garage_smoke_v2_carbon_monoxide_detected
    - binary_sensor.hallway_carbon_monoxide_status
    - binary_sensor.living_room_carbon_monoxide_status
  from: "off"
condition: []
action:
  service: script.text_notify_all
  data:
    message: >
      Carbon monoxide has been detected in the
      {% if area_name(trigger.entity_id) == none -%}
        house
      {%- else -%}
        area_name(trigger.entity_id)
      {%- endif  -%}
      !!
    title: WARNING!
    data:
      persistant: true
      push:
        sound:
          name: default
          critical: 1
          volume: 1
