---
id: "00050"
alias: Smoke Detected
description: "Send a warning that smoke was detected in the house."
mode: single
trigger:
  platform: state
  entity_id:
    - binary_sensor.guest_smoke_smoke_detected
    - binary_sensor.garage_smoke_v2_smoke_detected
    - binary_sensor.hallway_smoke_smoke_detected
    - binary_sensor.livingroom_smoke_smoke_detected
  from: "off"
condition: []
action:
  service: notify.ios_all
  data:
    title: WARNING!
    message: >
      Smoke detected in the
      {% if area_name(trigger.entity_id) == none -%}
        house
      {%- else -%}
        area_name(trigger.entity_id)
      {%- endif  -%}
      !!
    data:
      persistant: true
      push:
        sound:
          name: default
          critical: 1
          volume: 1
