---
id: "00021"
alias: "System: Start Habitica Day"
description: "Manually triggers the Habitica Cron via API call."
trigger:
  - platform: time
    at: "05:00:00"
action:
  - service: rest_command.habitica_cron
mode: single
