---
id: "00032"
alias: Bathroom Motion Lights
mode: restart
trigger:
  entity_id:
    - binary_sensor.bathroom_motion_detection
    - binary_sensor.ep1_bathroom_occupancy
  platform: state
  to: "on"
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: input_boolean.john_bed
                    state: "off"
                    for: 00:05:00
              - condition: time
                after: "22:00"
                before: 05:00
        sequence:
          - service: light.turn_on
            target:
              entity_id: >
                {{ 
                  [
                    "light.bathroom_sink_1",
                    "light.bathroom_sink_2", 
                    "light.bathroom_sink_3", 
                    "light.bathroom_sink_4" 
                  ] | random 
                }}
            data:
              brightness: 10
              color_temp_kelvin: 2202
              transition: 5
      - conditions:
          - condition: or
            conditions:
              - condition: sun
                before: sunrise
              - condition: sun
                after: sunset
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.sink_light
            data:
              brightness: 75
              color_temp_kelvin: 4000
              transition: 5
    default:
      - service: light.turn_on
        target:
          entity_id: light.sink_light
        data:
          brightness: 255
          color_temp_kelvin: 3101
          transition: 5
  - delay: "00:03:00"
  - service: light.turn_off
    target:
      entity_id: light.sink_light
    data:
      transition: 5
