---
id: "00045"
alias: Pause Bathroom Motion Triggers
mode: single
trigger:
  platform: device
  device_id: 99d88e062470eadce3e5ff19acd21f62
  domain: zha
  type: remote_button_short_press
  subtype: turn_on
action:
  - service: notify.alexa_media
    data:
      # yamllint disable-line rule:line-length
      message: <audio src="soundbank://soundlibrary/musical/amzn_sfx_electronic_beep_01"/>
      target: media_player.bathroom_flex
      data:
        type: tts
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.bathroom_motion_lights
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.bathroom_motion_lights
