---
id: "00021"
alias: Laundry Motion
mode: restart
max_exceeded: silent
trigger:
  type: motion
  platform: device
  device_id: 85f9d072b21917ee56ddcacebbc07eff
  entity_id: binary_sensor.laundry_motion_detection
  domain: binary_sensor
action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      transition: 1
    target:
      entity_id:
        - light.laundry_light
        - light.stairwell_light
  - wait_for_trigger:
      - type: no_motion
        platform: device
        device_id: 85f9d072b21917ee56ddcacebbc07eff
        entity_id: binary_sensor.laundry_motion_detection
        domain: binary_sensor
        for:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
      - type: no_motion
        platform: device
        device_id: 0fa6549078e1f67cdde0e705b2e0f20b
        entity_id: binary_sensor.stairwell_motion
        domain: binary_sensor
        for:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
  - service: light.turn_off
    data:
      transition: 15
    target:
      entity_id:
        - light.laundry_light
        - light.stairwell_light
