---
id: "00020"
alias: Stairwell Motion
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.stairwell_motion
    from: "off"
    to: "on"
action:
  - service: light.turn_on
    data:
      transition: 1
      brightness_pct: 100
    target:
      entity_id:
        - light.laundry_light
        - light.stairwell_light
  - delay:
      minutes: 5
  - service: light.turn_off
    data:
      transition: 15
    target:
      entity_id:
        - light.laundry_light
        - light.stairwell_light
