---
id: "00020"
alias: Stairwell Motion
mode: restart
max_exceeded: silent
trigger:
  domain: binary_sensor
  entity_id: binary_sensor.stairwell_motion
  platform: device
  type: motion
action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      transition: 1
    target:
      entity_id:
        - light.laundry_light
        - light.stairwell_light
  - delay:
      minutes: 5
  - service: light.turn_off
    data:
      transition: 15
    target:
      entity_id:
        - light.laundry_light
        - light.stairwell_light
