---
id: "00060"
alias: Welcome John Home
mode: single
trigger:
  - platform: zone
    entity_id: person.john
    zone: zone.home
    event: enter
action:
  - service: conversation.process
    data:
      agent_id: conversation.openai_conversation
      text: Welcome John Home
    response_variable: welcome_response
  - service: notify.alexa_media
    data:
      title: Welcome Home John
      # yamllint disable rule:line-length
      message: "{{ welcome_response.response.speech.plain.speech }}"
      # yamllint enable rule:line-length
      target:
        - media_player.living_room_dot
        - media_player.computer_room_spot
      data:
        type: announce
