---
id: "00053"
alias: Ulanzi Recharge Stop
description: "Turn off power to recharge Ulanzi display"
mode: single
trigger:
  - platform: numeric_state
    entity_id: sensor.awtrix_4200c8_battery
    above: 80.0
action:
  - service: switch.turn_off
    target:
      entity_id: switch.ulanzi_power_source
