---
id: "00002"
alias: JE Medicine Reminder AM
initial_state: true
trigger:
  - platform: time_pattern
    minutes: "/15"
    seconds: "00"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.je_medicine
        state: "off"
      - condition: time
        after: "06:30:00"
      - condition: time
        before: "18:30:00"
action:
  - action: conversation.process
    data:
      agent_id: conversation.openai_conversation
      text: >-
        Your objective is to get John to take their morning medicines.
        Your response should be two sentences or less. 
    response_variable: response_var
  - service: script.text_notify_john
    data:
      title: "Medication Alert!"
      message: "{{ response_var.response.speech.plain.speech }}"
      data:
        actions:
          - action: "JE_MEDS_TAKEN"
            title: "Medication Taken"
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:pills"
          - action: "JE_MEDS_SNOOZE"
            title: "Snooze 3 hrs."
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:powersleep"
