---
id: "00003"
alias: JE Remind Me Later
mode: restart
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: JE_MEDS_SNOOZE
action:
  - service: script.text_notify_john
    data:
      title: "💤 Snooze"
      # yamllint disable rule:line-length
      message: >
        {{
          [
            "Putting the 'do not disturb' sign on my medication reminders for the next 180 minutes.",
            "Sending my motivation on a three-hour siesta.",
            "Temporarily hibernating my to-do list for a solid quad-hour.",
            "Initiating a three-hour hiatus from adulting - catch you on the flip side!",
            "Pressing the 'snooze' button on life for the duration of an afternoon nap.",
            "Granting myself a PhD in procrastination for the next 180 minutes.",
            "Launching Operation: Sleep Mode for the next three hours - over and out!",
            "Bidding farewell to responsibility until the clock strikes three hours from now.",
            "Entering stealth mode for a tactical three-hour recharge.",
            'Officially taking a break from reminders... see you in 3 hours!'
          ] | random
        }}
      # yamllint enable rule:line-length
      data: {}
  - service: automation.turn_off
    target:
      entity_id:
        - automation.je_medicine_reminder_am
        - automation.je_medicine_reminder_pm
  - delay:
      hours: 3
      minutes: 0
      seconds: 0
  - service: automation.turn_on
    target:
      entity_id:
        - automation.je_medicine_reminder_am
        - automation.je_medicine_reminder_pm
