---
id: "00002"
alias: JE Medicine Reminder AM
initial_state: true
trigger:
  - platform: time_pattern
    minutes: "/15"
    seconds: "00"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.je_medicine
        state: "off"
      - condition: time
        after: "06:30:00"
      - condition: time
        before: "18:30:00"
action:
  - service: script.text_notify_john
    data:
      title: "Medication Alert!"
      message: "Please take your daily medicine!"
      data:
        actions:
          - action: "JE_MEDS_TAKEN"
            title: "Medication Taken"
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:pills"
          - action: "JE_MEDS_SNOOZE"
            title: "Snooze 3 hrs."
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:powersleep"
