---
id: "00002"
alias: JE Medicine Reminder
initial_state: true
trigger:
  - platform: time_pattern
    minutes: "/15"
    seconds: "00"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bp_medicine
        state: "off"
      - condition: time
        after: "06:30:00"
action:
  - service: script.text_notify_john
    data:
      title: "Medicine Alert!"
      message: "Please take your daily medicine!"
      data:
        actions:
          - action: "BP_TABLET_TAKEN"
            title: "BP Tablet Taken"
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:pills"
          - action: "BP_TABLET_SNOOZE"
            title: "BP Tablet Snooze"
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:powersleep"
