---
id: "000xx"
alias: JE Testosterone Taken
mode: single
trigger:
  - device_id: 99d88e062470eadce3e5ff19acd21f62
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: dim_down
condition: []
action:
  - service: counter.decrement
    target:
      entity_id: counter.test_medicine_counter
  - service: notify.alexa_media
    data:
      target: media_player.bathroom_flex
      data:
        type: tts
      message: >-
        <audio
        src="soundbank://soundlibrary/computers/beeps_tones/beeps_tones_08"/>
  - if:
      - condition: numeric_state
        entity_id: counter.test_medicine_counter
        below: 2
    then:
      - service: notify.alexa_media
        data:
          target: media_player.bathroom_flex
          data:
            message: >
              Your testosterone prescription is low with
              {% if int(states("counter.test_medicine_counter")) == 1 -%}
                {{  states("counter.test_medicine_counter") }} dose left.
              {%- else -%}
                {{  states("counter.test_medicine_counter") }} doses left.
              {%- endif %}
