substitutions:
  name: ep1-den

packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: "EP1 Den"

ota:
  platform: esphome
  password: !secret ota_password    

api:
  encryption:
    key: !secret esphome_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
