---
substitutions:
  devicename: waveshare-display
  upper_devicename: WaveShare-Display
  short_name: WaveShare

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption_key

captive_portal:

ch422g:
  - id: ch422g_hub

color:
  - id: color_blue
    red_int: 0
    green_int: 0
    blue_int: 255
    white_int: 0
  - id: color_teal
    red_int: 0
    green_int: 255
    blue_int: 255
    white_int: 0
  - id: color_orange
    red_int: 243
    green_int: 156
    blue_int: 18
    white_int: 0

display:
  - platform: rpi_dpi_rgb
    id: jarvis_display
    auto_clear_enabled: false
    update_interval: never
    color_order: RGB
    pclk_frequency: 14MHz #16MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: false
    hsync_back_porch: 30
    hsync_front_porch: 210
    hsync_pulse_width: 30
    vsync_back_porch: 4
    vsync_front_porch: 4
    vsync_pulse_width: 4
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7

esphome:
  name: ${devicename}
  friendly_name: ${short_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # CONFIG_COMPILER_OPTIMIZATION_PERF: y
      # CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      # CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      # CONFIG_ESPTOOLPY_FLASHFREQ_120M: y #[should align with PSRAM]
      # CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      # CONFIG_FREERTOS_HZ: '1000'
      # CONFIG_IDF_EXPERIMENTAL_FEATURES: y #[should align with PSRAM]
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      # CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_SPIRAM_RODATA: y
      # CONFIG_SPIRAM_SPEED_120M: y #[should align with PSRAM]

font:
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: roboto_h1
    size: 40
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: roboto_body
    size: 20

globals:
  - id: random_int_var
    type: int
    restore_value: no
    initial_value: '0'

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: True
  id: bus_a

image:
  - file: mdi:home-assistant
    id: img_ha
    resize: 200x200
  - file: mdi:controller
    id: img_controller
    resize: 200x200
  - file: mdi:cogs
    id: img_settings
    resize: 200x200
  - file: mdi:sun-wireless-outline
    id: solar_power_icon
    resize: 50x50

logger:

binary_sensor:
  - platform: lvgl
    widget: button
    name: Button
    on_press: # genrate a random number between -10 and +10 and update meter
      then:
        - lambda: |-
            id(random_int_var) = (rand() % 20) - 10;
        - lvgl.indicator.update:
            id: power_meter_input
            value: !lambda return id(random_int_var);
        - lvgl.label.update:
            id: power_kw
            text:
              format: "%dkW"
              args: [ 'id(random_int_var)' ]


lvgl:
  displays:
    - jarvis_display
  # pages:
  #   - id: welcome_page
  #     widgets:
  #       - label:
  #           align: CENTER
  #           text: "Honey Haus"
  log_level: INFO
  color_depth: 16
  bg_color: 0
  border_width: 0
  outline_width: 0
  shadow_width: 0
  text_font: roboto_h1
  align: center
  style_definitions:
    - id: meter_style
      border_width: 0
      outline_width: 0
      align: center
      bg_color: 0
    - id: title_style
      text_font: MONTSERRAT_40
      align: center
      text_color: 0xFFFFFF
      bg_opa: TRANSP
      bg_color: 0
      radius: 4
      pad_all: 2
    - id: detail_style
      text_font: MONTSERRAT_18
      align: center
      text_color: 0xFFFFFF
      bg_opa: TRANSP
      bg_color: 0
      radius: 4
      pad_all: 2
  widgets:
    - button: # Button
        id: button
        height: 100
        width: 200
        x: 20
        y: 20
        border_width: 0
        outline_width: 0
        align: TOP_LEFT
        checkable: false
        widgets:
        - label:
            align: center
            text: "Button"
    - obj: # Meter
        height: 240
        width: 240
        bg_color: 0
        border_width: 0
        outline_width: 0
        shadow_width: 0
        pad_all: 4
        align: TOP_MID
        widgets:
          - meter: # Gradient color  arc
              height: 100%
              width: 100%
              border_width: 0
              outline_width: 0
              align: center
              bg_color: 0
              scales:
                angle_range: 180
                range_to: 10
                range_from: -10
                ticks:
                  count: 0
                indicators:
                  - line:
                      id: power_meter_input
                      width: 8
                      color: 0xFFFFFF
                      r_mod: 12
                      value: 50
                  - arc:
                      color: 0xFF3000
                      r_mod: 10
                      width: 20
                      start_value: -10
                      end_value: 0
                  - arc:
                      color: 0x00FF00
                      r_mod: 10
                      width: 20
                      start_value: 0
                      end_value: 10
          - arc: # black arc to erase middle part of meter indicator line
              height: 160
              width: 160
              align: center
              arc_color: 0x000000
              arc_width: 150
              start_angle: 0
              end_angle: 360
              indicator:
                arc_width: 150
                arc_color: 0x000000
          - label: # gauge lower and higher range indicators
              styles: detail_style
              y: 8
              x: -99
              text: "-10"
          - label:
              styles: detail_style
              y: 8
              x: 99
              text: "+10"
          - label:  # value label
              styles: title_style
              id: power_kw
              y: -10
          - image:
              src: solar_power_icon
              id: img_solar_power
              align: center
              image_recolor: 0xFFFF00
              image_recolor_opa: 100%
              y: 50
        


ota:
  - platform: esphome
    password: !secret ota_password

psram:
  mode: octal
  speed: 80MHz

switch:
  - platform: gpio
    name: "Display Backlight"
    pin:
      ch422g: ch422g_hub
      number: 2
      mode:
        output: true
      inverted: false
    restore_mode: ALWAYS_ON
#   - platform: gpio
#     name: "Touch Reset"
#     pin:
#       ch422g: ch422g_hub
#       number: 1
#       mode:
#         output: true
#       inverted: false
#   - platform: gpio
#     name: "LCD Reset"
#     pin:
#       ch422g: ch422g_hub
#       number: 3
#       mode:
#         output: true
#       inverted: false

time:
  - platform: homeassistant
    id: homeassistant_time

touchscreen:
  platform: gt911
  id: my_touch
  interrupt_pin: GPIO4
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );

web_server:
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  include_internal: True
  port: 8080
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $short_name Fallback Hotspot
    password: !secret ap_password
