---
id: "00014"
alias: Metformin AM Reminder
initial_state: true
trigger:
  - platform: time_pattern
    minutes: "/15"
    seconds: "00"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.mf_medicine
        state: "off"
      - condition: time
        after: "08:00:00"
action:
  - service: script.text_notify_robert
    data:
      title: "Metformin Alert!"
      message: "Please take your morning medicine!"
      data:
        actions:
          - action: "MF_TABLET_TAKEN"
            title: "Medicine Taken"
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:pills"
          - action: "MF_TABLET_SNOOZE"
            title: "Snooze 4 hrs."
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:powersleep"
