---
id: "00018"
alias: RB Medicine PM Reminder
initial_state: true
trigger:
  - platform: time_pattern
    minutes: "/15"
    seconds: "00"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.rb_medicine
        state: "off"
      - condition: time
        after: "18:30:00"
action:
  - service: script.text_notify_robert
    data:
      title: "Medication Alert!"
      message: "Please take your evening medicine!"
      data:
        actions:
          - action: "MF_TABLET_TAKEN"
            title: "Medicine Taken"
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:pills"
          - action: "MF_TABLET_SNOOZE"
            title: "Snooze 3 hrs."
            activationMode: "background"
            authenticationRequired: false
            destructive: false
            icon: "sfsymbols:powersleep"
