---
id: "00066"
alias: Stock Ticker
description: "Display stock prices on AWTRIX"
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.yahoofinance_aapl
      - sensor.yahoofinance_icln
      - sensor.yahoofinance_schd
      - sensor.yahoofinance_xrt
      - sensor.yahoofinance_tmus
      - sensor.yahoofinance_mgc
    attribute: regularMarketPrice
condition: []
action:
  - variables:
      # take out the space from the join on the next line before production
      entity_list: >
        {{ states.sensor | selectattr('entity_id', 'search', '^sensor\\.yahoofinance') | map(attribute='entity_id') | join(', ') }}
  - repeat:
      count: "{{ entity_list.split(',') | length }}"
      sequence:
        - variables:
            stock_icon: >-
              {% set icon_key = state_attr(entity_list.split(',')[repeat.index - 1] | trim, 'trending') %}
              {% set icon_values =
                {
                  "up": "120",
                  "down": "124"
                }
              %}
              {{ icon_values.get(icon_key, '507') }}

        - service: mqtt.publish
          data:
            qos: 0
            # yamllint disable rule:line-length
            topic: awtrix_4200c8/custom/yahoofinance_{{ state_attr(entity_list.split(',')[repeat.index - 1] | trim, 'symbol') }}
            payload_template: |-
              {
                "text": "{{ state_attr(entity_list.split(',')[repeat.index - 1] | trim, 'friendly_name') }} ({{ state_attr(entity_list.split(',')[repeat.index - 1] | trim, 'symbol') }}) - {{ state_attr(entity_list.split(',')[repeat.index - 1] | trim, 'currencySymbol')  }}{{ state_attr(entity_list.split(',')[repeat.index - 1] | trim, 'regularMarketPrice')  }}" ,
                "icon": "{{ stock_icon }}"
              }
            # yamllint enable rule:line-length
