---
id: "00063"
alias: "Network Upload Speed"
description: ""
mode: single
trigger:
  - platform: time_pattern
    minutes: "20"
condition:
  - condition: state
    entity_id: light.awtrix_4200c8_matrix
    state: "on"
action:
  - service: mqtt.publish
    data:
      # yamllint disable rule:line-length
      payload: |-
        {
          "duration": 10,
          "icon": "upload",
          "text": "Upload speed is {{ '%.0f' | format(state_attr('sensor.speedtest_upload', 'bytes_sent')/1000000)  }} Mbs  /s",
          "textCase": 2,
          "textOffset": 33
        }
      # yamllint enable rule:line-length
      qos: 0
      retain: false
      topic: awtrix_4200c8/custom/speedtest_up
