---
id: "00054"
alias: Ulanzi Rain
description: shows the local rain data
trigger:
  - platform: state
    entity_id: sensor.netatmo_netatmo_indoor_rain_gauge_rain
variables:
  rain_now: >-
    {{
      states("sensor.netatmo_netatmo_indoor_rain_gauge_rain")
      | float(2)
    }}
  rain_day: >-
    {{
      states("sensor.netatmo_netatmo_indoor_rain_gauge_rain_today")
      | float(2)
    }}
  rain_text: >-
    {% if rain_now > 0 %}
      Current Rain: {{ rain_now }}
      {{
        state_attr(
          "sensor.netatmo_netatmo_indoor_rain_gauge_rain",
          "unit_of_measurement"
        )
      }}
    {% endif %}
    Total Rain: {{ rain_day }} {{
        state_attr(
          "sensor.netatmo_netatmo_indoor_rain_gauge_rain",
          "unit_of_measurement"
        )
      }}
action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: awtrix_4200c8/custom/netatmo_rain
      payload: |-
        {
          "text": "{{ rain_text }}!",
          "icon": "41619",
          "repeat": 5,
          "duration": 10,
          "overlay": "rain"
        }

