---
id: "00067"
alias: Ulanzi No Rain
description: shows the local rain data
initial_state: false
# No change for 30 minutes
trigger:
  platform: state
  entity_id:
    - sensor.netatmo_netatmo_outdoor_rain_guage_rain
    - sensor.netatmo_netatmo_outdoor_rain_guage_rain_last_hour
    - sensor.netatmo_netatmo_outdoor_rain_guage_rain_today
variables:
  rain_day: >-
    {{
      states("sensor.netatmo_netatmo_indoor_rain_gauge_rain_today")
      | float(2)
    }}
  rain_text: "Total Rain: {{ rain_day }} in"
action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: awtrix_4200c8/custom/netatmo_rain
      payload: |-
        {
          "text": "{{ rain_text }}",
          "icon": "41619",
          "repeat": 5,
          "duration": 10,
          "overlay": "clear"
        }
