---
id: "00046"
alias: AWTRIX Weather
description: shows the local weatherdata with the icon based on cloud service
trigger:
  - platform: state
    entity_id: weather.honey_haus
variables:
  weather_icon: >-
    {% set icon_key = states('weather.honey_haus') %}
    {% set icon_values =
      {
        "clear_night": "53383",
        "cloudy": "53384",
        "exceptional": "5464",
        "fog": "56703",
        "hail": "53385",
        "humidity": "51764",
        "lightning_rainy": "49299",
        "lightning": "50231",
        "partlycloudy": "53802",
        "pouring": "49300",
        "rainy": "2284",
        "snowy_rainy": "49301",
        "snowy": "2289",
        "sunny": "11201",
        "temp": "2056",
        "windspeed": "7789",
        "windy_variant": "15618",
        "windy": "17076"
      }
    %}
    {{ icon_values.get(icon_key, '1246') }}
  air_temp: >-
    {{ state_attr('weather.honey_haus', 'temperature') }}
    {{ state_attr('weather.honey_haus', 'temperature_unit') }}
  humid_info: >-
    {{ state_attr('weather.honey_haus', 'humidity') }}%
  wind_dir: >-
    {% set direction = [
      'N',
      'NNE',
      'NE',
      'ENE',
      'E',
      'ESE',
      'SE',
      'SSE',
      'S',
      'SSW',
      'SW',
      'WSW',
      'W',
      'WNW',
      'NW',
      'NNW',
      'N'
    ] %}
    {% set degree = state_attr('weather.honey_haus', 'wind_bearing')|float(0) %}
    {{ direction[ (( degree + 11.25) / 22.5) | int] }}
  wind_info: >-
    {{ state_attr('weather.honey_haus', 'wind_speed') | round }}
    {{ state_attr('weather.honey_haus', 'wind_speed_unit') }}
action:
  - service: mqtt.publish
    metadata: {}
    data:
      topic: awtrix_4200c8/custom/HA_Weather
      # yamllint disable rule:line-length
      payload: |-
        {
          "text": "Temp: {{ air_temp }} Humid: {{ humid_info }} Wind: {{ wind_info }} ({{ wind_dir }})",
          "textCase": 1,
          "icon": "{{ weather_icon }}",
          "repeat": 2,
          "duration": 5,
          "stack": 0
        }
      # yamllint enable rule:line-length
      qos: 0
      retain: false
